### ISSUE TITLE
Another ignorant repository.

### ISSUE THREAD

**Issue by Admin9961** [ssh-mitm/ssh-mitm#125]
### What feature you'd like to see or proposal

Poorly exmplained and completely bugged.

**Comment by manfred-kaiser** [comment]
This is my free time project and it's an open source project. 

If you think something is missing, you are welcome to contribute 😉

**Comment by Admin9961** [comment]
This is a tool meant for defense and stopping skiddies, all installation methods are bugged , the .exe doesn't even work in wine i386, and it's poorly explained

**Comment by manfred-kaiser** [comment]
> This is a tool meant for defense and stopping skiddies, 

I think you have created this issue for the wrong project. This tool does not protect you from attacks and is not intended for script kiddies. 

If you want to use this tool, you shoud have already some knowlegde in penetration testing. 

> all installation methods are bugged , the .exe doesn't even work in wine i386, and it's poorly explained

In current versions of windows, 32bit is no longer supported. you should use a recent and supported windows version to get security updates.

The windows version should run with Linux using Wine. But you must use 64bit wine, because 32bit are not supported due to the mentioned reasons 

Perhaps you mean, that we should provide a 32bit version for windows.

Please feel free to create a 32bit version for windows and create a pull request. This is the way open source software works. Thanks in advance for your contribution 👍😉
