### ISSUE TITLE
Port forwarding and x11?

### ISSUE THREAD

**Issue by litheory** [ssh-mitm/ssh-mitm#13]
Is there a plan for port forwarding and x11 channel, or these is developing?

**Comment by manfred-kaiser** [comment]
i want to implement port forwarding, because it is interesting for security audits. port forwarding can be compared with raw tcp interception.
Port forwarding will be supported by another library, which will handle raw tcp connections and the ssh proxy server will use this library to handle the intercepted traffic from the forwarded port.
The new proxy will also support SOCKS4 and parts of SOCKS5.
At the moment, I have no release date for the tcp proxy library.

X11 forwarding will not be supported. Forwarding the data from the client to the server and vice versa should not be difficult, but what should we do with the data? Handling the X11 protocol is not an easy task, especially if you don't have a X11 server on the proxy. There also might be some security considerations, handling X11 on the proxy.

So there is not plan to support X11 forwarding.

**Comment by manfred-kaiser** [comment]
Logging of X11 could be possible: https://pypi.org/project/xlib/

Differences between X11, Wayland, ... are described in this artice: https://venam.nixers.net/blog/unix/2016/10/25/x11-blah-blah.html

Xlib documentation: https://tronche.com/gui/x/xlib/

**Comment by manfred-kaiser** [comment]
port forwarding is implemented in release 0.4.0.

At the moment the port is only forwarded to the proxy, but forwarding the port to the remote server will be implemented in one of the next releases

**Comment by manfred-kaiser** [comment]
Version 0.5.0 has full support for port forwarding.

X11 forwarding is currently not on the road map and not planned to be integrated. So I will close this issue.
