### ISSUE TITLE
Support server listening to specific interface

### ISSUE THREAD

**Issue by elvanowen** [ssh-mitm/ssh-mitm#162]
### What feature you'd like to see or proposal

Currently the server will listen to 0.0.0.0 address with no option to be configured. There might be case we don't want it to listen to all interfaces, e.g. if we only want it to listen to loopback interface 127.0.0.1.

**Comment by manfred-kaiser** [comment]
Thanks for the suggestion. I will implement it in the next release.

Should the server start with 0.0.0.0 or with localhost?

Most applications are using localhost, because it's more secure, but my intention was to start SSH-MITM with 0.0.0.0 to allow all connections without further configuration.

Perhaps I will leave 0.0.0.0 as the default but make it configurable.

**Comment by elvanowen** [comment]
Thanks Manfred.

Yes, I agree to keep the default 0.0.0.0 the same to prevent causing breaking change. 

I think we could let user specify the ip address to be configured since a server could have multiple different interfaces with different ip address.

Let me know what you think.
