### ISSUE TITLE
Redirect commands for inspection

### ISSUE THREAD

**Issue by aiesam** [ssh-mitm/ssh-mitm#48]
I am not sure if this is possible with ssh-mitm, but I'll give it a try. I am looking at redirecting all commands that the client enters after ssh login is completed. The reason is that i need to automatedly allow certain commands and deny certain commands. The destination server is not within my control, so i am unable to do this there, but i am hoping I could monitor all commands via ssh-mitm. Any ideas?

**Comment by manfred-kaiser** [comment]
Monitoring commands is possible. If you only need a logfile, you can start ssh-mitm with `ssh-mitm --ssh-interface sessionlogger --ssh-log-dir ~/sshlogs`  

This will create a folder for each session. In this folder, you can find the input and the output. The output also contains visible input. If you want to get passwords from sudo, you have to look at the input file. The reason is, that passwords are not visible in the shell.

If you want to allow or deny certain commands, you can write your own plugin, but there are some problems.

1. The command is sent as single characters. You have to create a buffer and store each character to get the full command
2. You must handle newlines. A newline can execute the command or is only a newline. So you have to implement a parser which can understand the shell synthax
3. A user can use !! to call the last command. You have to implement a command history
4. A user can use shell variables to execute a command
5. ...

If you want to create a plugin for this usecase, you can clone or download the ssh-mitm-plugins reposiroty: https://github.com/ssh-mitm/ssh-mitm-plugins

Create a new file in `ssh_mitm_plugins/ssh/`. For example `checkcommand.py`.

Example Plugin:

```python
import logging
from ssh_proxy_server.forwarders.ssh import SSHForwarder

class SSHCheckCommandForwarder(SSHForwarder):

    def __init__(self, session):
        super().__init__(session)
        self.command_buffer = b""

    def stdin(self, text):
        if text == b'\x7f' and len(self.command_buffer) > 0:
            self.command_buffer = self.command_buffer[:-1]
        elif text == b"\r":
            command = self.command_buffer
            self.command_buffer = b""
            if command in [b"ls", b"vim"]:
                logging.error("command %s forbidden", command)
                return b'\x7f' * len(command)
        else:
            self.command_buffer += text
        return text
```

Then edit the file `ssh_mitm_plugins/__entrypoints__.py`. In this file you have to add a new entrypoint.

```python
entry_points = {
    'SSHBaseForwarder': [
        'scriptedshell = ssh_mitm_plugins.ssh.scriptedshell:SSHScriptedForwarder',
        'stealthshell = ssh_mitm_plugins.ssh.stealthshell:SSHStealthForwarder',
        'injectorshell = ssh_mitm_plugins.ssh.injectorshell:SSHInjectableForwarder',
        'checkcommand = ssh_mitm_plugins.ssh.injectorshell:SSHCheckCommandForwarder',
    ],
    'SCPBaseForwarder': [

    ],
    'BaseSFTPServerInterface': [

    ],
    'SFTPHandlerBasePlugin': [

    ]
}
```

Install the updated package with `pip install -U /path/to/ssh_mitm_plugins_repo`

**Info:**

If you want, you can share your final plugin with us by creating a pull request to ssh-mitm-plugins ;-)

**Comment by manfred-kaiser** [comment]
> The reason is that i need to automatedly allow certain commands and deny certain commands. The destination server is not within my control

I don't recommend using ssh-mitm for restricting users. ssh-mitm is a tool for security audits and not a jump host. This is described in: https://docs.ssh-mitm.at/jumphosts.html

If you need a jump host for compliance reasons, there are better products.

**Using ssh-mitm as jump host is a security risk! Don't use it in your network, except for security audits**

**Comment by aiesam** [comment]
Thanks Mansfred!
