### ISSUE TITLE
MITM doesn't work

### ISSUE THREAD

**Issue by Gregoryash** [ssh-mitm/ssh-mitm#55]
Client gets "Permission denied, please try again." (correct password entered). ssh-mitm is running in transparent mode on Ubuntu 18
[log.txt](https://github.com/ssh-mitm/ssh-mitm/files/6570638/log.txt)

**Comment by manfred-kaiser** [comment]
You are getting an ipv4 address, converted to an ipv6 address. The prefix ::ffff: is a ipv6 subnet for ipv4 addresses.

When looking at the log file, it seems, that paramiko have erros parsing the destination addess and the port.
The reason is, that the destination parameter was a string and not a tuple :-(

I have created a new bug fix release 0.5.5. You can update your installation with ``pip install -U ssh-mitm``

Can you test it please.

**Comment by Gregoryash** [comment]
Works, thanks
