### ISSUE TITLE
ssh-mitm is not able to intercept traffic from proxifier and sockd (socks5)

### ISSUE THREAD

**Issue by Gregoryash** [ssh-mitm/ssh-mitm#56]
I'm trying to intercept SSH connections going from my SOCKS5 server. When I type "ssh 185.163.45.155 -l root" on my SOCKS server everything works fine (log1.txt), but when I connect from another client using my proxy server and type "ssh 185.163.45.155 -l root" it stuck after accepting password (log2.txt). When I disable traffic redirection to ssh-mitm everything works fine. 

[log2.txt](https://github.com/ssh-mitm/ssh-mitm/files/6572189/log2.txt)

[log1.txt](https://github.com/ssh-mitm/ssh-mitm/files/6572188/log1.txt)

**Comment by Gregoryash** [comment]
ssh-mitm is installed on an Ubuntu 18 (server 1). This server is used as a gateway by server 2. Server 2 is running Ubuntu 18 and sockd on it. Traffic is redirected to ssh-mitm with the following iptables rules:
iptables -t mangle -I PREROUTING -p tcp --dport 22 -j TPROXY --tproxy-mark 1 --on-port 14000 --on-ip 127.0.0.1
iptables -t mangle -A PREROUTING -m tcp -p tcp --sport 22 -j MARK --set-mark 1
ip rule add fwmark 1 lookup 100
ip route add local default dev lo table 200

**Comment by manfred-kaiser** [comment]
> Server 2 is running Ubuntu 18 and sockd on it.

Are you using sockd to intercept the ssh traffic and redirecting it to ssh-mitm or why are you using it?

When using ssh-mitm's TProxy feature to intercept ssh traffic, you should not need to setup a proxy server like sockd for ssh. Using the ssh-mitm server as gateway should be enough. If you need to intercept other protocols too, you have to redirect that traffic to another proxy server, but keep redirecting ssh sessions to ssh-mitm.

Why are you using socks5? 

Socks5 is not part of the ssh protocol and ssh-mitm does not support socks. OpenSSH has an implemented socks5 server, but this feature is only available in OpenSSH and not part of the ssh protocol. The openssh client starts a socks server, which allows a socks 5 client like browsers to use port forwarding. When a client wants to connect to another server through the socks protocol, a port forwarding request is created. Between the ssh client and the ssh server, there is not socks protocol.

I think, removing sockd from your setup should fix your problem. If you need to intercept ssh connections and other protocols, the easiest way is to install ssh-mitm and sockd on the same machine. Using different machines and redirecting the traffic between them can break your connections. If the first machine does not support transparent connections, you are loosing the source or destination address.

**Comment by Gregoryash** [comment]
Yes, I'm trying to intercept SSH connections going through my proxy server. I want to show people why it's a bad idea to use public proxies.

-Between the ssh client and the ssh server, there is no socks protocol
I use proxifier on a client machine

- If you need to intercept ssh connections and other protocols, the easiest way is to install ssh-mitm and sockd on the same machine
I don't know how to redirect sockd traffic to ssh-mitm

**Comment by manfred-kaiser** [comment]
I have not used proxifier, so I don't know how to configure the client :-(
But from the description, I think, that the whole client traffic is routed through sockd. Is this correct?

Please remove all iptables rules to test you setup without transparent mode. We want to configure a direct connection to the ssh server for this tests.

Have you tried to connect to the ssh server without ssh-mitm? I think this should work. If this does not work, you have to change your setup.

If you can establish ssh connections, you can try the same setup with ssh-mitm. You can start ssh-mitm and provide a destination host and port ``ssh-mitm --remote-host TARGETHOST --remote-port 22``. If the previous test worked, this should also work.

Can you test this two scenarios please.

**Comment by manfred-kaiser** [comment]
If the previous tests worked, you can try the transparent mode without proxifier and sockd.

Configure the server with ssh-mitm as default gateway or add a new route, which is using the server as gateway.

Setup firewall rules on the ssh-mitm server:

**Using iptables:**

``$ iptables -t mangle -A PREROUTING -p tcp --dport 22 -j TPROXY --tproxy-mark 0x1/0x1 --on-port=10022 --on-ip=127.0.0.1``

**Or using firewalld:**

``firewall-cmd --direct --permanent --add-rule ipv4 mangle PREROUTING 1 -p tcp --dport 22 --j TPROXY --tproxy-mark 0x1/0x1 --on-port=10022 --on-ip=127.0.0.1``


Start ssh-mitm in transparent mode: 

``$ ssh-mitm --transparent``


When you connect to a server in a network, which is routed through ssh-mitm's server, ssh-mitm should be able to intercept the connection.

**Comment by Gregoryash** [comment]
-Have you tried to connect to the ssh server without ssh-mitm? I think this should work. If this does not work, you have to change your setup
It works 
I can't provide a destination IP to ssh-mitm, I need it to work with all IPs.

**Comment by manfred-kaiser** [comment]
> I can't provide a destination IP to ssh-mitm, I need it to work with all IPs.

You should have a test ssh server in your scenario. Please test, if ssh-mitm is working without transparent mode.

Are you using IPv4 and/or IPv6? If you have IPv6 you have to setup the rules for it too.

You are using password authentication. SSH-MITM asks for the password. This is the authentication step you mentioned.
after the authentication step, ssh-mitm tries to connect to the destination server.

You can use wireshark to debug the connection. With wireshark you can monitor, if the tcp packets are sent to the destination server and you should also see the response. If the tcp connection does not work, you will see the reason. e.g. wrong destination, packet loss, routing errors, ...

I can not test you scenario, because Proxifier is only a Windows and a Mac application and setting up your scenario is very time consuming. (I work on ssh-mitm in my free time)

Intercepting ssh traffic in transparent mode can become complicated. Without the same setup, I can only guess, why it is not working.

**Comment by manfred-kaiser** [comment]
Your second connection (log2.txt) was able to authenticate to the remote server. But you get stuck after that step.

Your client sends a ``check_channel_pty_request``, a ``check_channel_env_request`` and a ``check_channel_shell_request``. 
Those requests are only handled by ssh-mitm and are not forwarded to the destination server.

Your session can be started. This means, that you have a working connection between your client->ssh-mitm and ssh-mitm->destination.

The forwarder for your shell session was initialised, but the mirror shell was not successfully started. The mirror shell is the default forwarder.

Perhaps the mirror shell forwarder does not work in you setup. This forwarder opens an additional port, which can be used to hijack the connection. I think you get stuck in this step, because the mirror forwarder is not able to establish required network connections. This forwarder uses some name lookups to bind the address and make connection to the mirror shell easier for the user.

You can try the base shell forwarder: ``ssh-mitm --ssh-interface base --transparent``

The base forwarder only forwards the session from the client to the server.

If the base forwarder works and you need a session log, you can use the ``sessionlogger`` shell forwarder. This forwarder stores the complete session in an input and in an output file. The outputfile is compatible with ``scriptreplay`` or you can use ``tail -f outputfile`` to watch a live session.

@Gregoryash please try your setup with the base shell forwarder: ``ssh-mitm --ssh-interface base --transparent``

**Comment by Gregoryash** [comment]
-Are you using IPv4 and/or IPv6?
I connect by IPv4

I have tested --ssh-interface base, --remote-host TARGETHOST --remote-port 22 and both of them combined. In all of 3 cases I saw the same behavior and same output.

**Comment by manfred-kaiser** [comment]
have you tried '--remote-host TARGETHOST --remote-port 22' without transparent mode?

If ssh-mitm works without transparent mode, you can try another linux distribution or Ubuntu version.

There are some combinations of python versions and kernel versions, where TProxy does not reliable work. Even a kernel update didn't fix this problem.

Centos 7 with python 3.6 from the software collection works without any problems in transparent mode.

**Comment by Gregoryash** [comment]
-have you tried '--remote-host TARGETHOST --remote-port 22' without transparent mode?
No

I tried on CentOS 7 with transparent mode, it had the same problem as I described in the first message.

**Comment by manfred-kaiser** [comment]
> I tried on CentOS 7 with transparent mode, it had the same problem as I described in the first message.

thats strange 😐

**Comment by manfred-kaiser** [comment]
Perhaps the TProxy kernel module is not loaded. If the command ``lsmod | grep TProxy`` does not have any output, you have to load the kernel module.

TProxy should be available on most linux distributions without additional installation.

Following commands are rom my dev/test documentation. Perhaps the published documentation was missing some important information.

-------

**Enable ip_forward to forward packets:**

```
echo 1 > /proc/sys/net/ipv4/ip_forward
```

**Load TProxy:**

Check if TProxy is enabled:

```
lsmod | grep TProxy
```

If you don't have some output, TProxy is not enabled. Load it with: 

```
modprobe xt_TPROXY
```

Check again, if TProxy is loaded:

```
$ lsmod | grep TPROXY
xt_TPROXY              20480  0
nf_tproxy_ipv6         20480  1 xt_TPROXY
nf_tproxy_ipv4         20480  1 xt_TPROXY
nf_defrag_ipv6         24576  2 nf_conntrack,xt_TPROXY
nf_defrag_ipv4         16384  2 nf_conntrack,xt_TPROXY
x_tables               49152  6 xt_conntrack,iptable_filter,xt_addrtype,xt_TPROXY,ip_tables,xt_MASQUERADE
```

**Create iptables and routing rules:**

You already have those rules, but I add them for completeness:

```
# create a chain "DIVERT"
iptables -t mangle -N DIVERT
# if we have a socket, jump to the previously created "DIVERT" chain.
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
# in DIVERT, we can do more but we only need to accept the connection
iptables -t mangle -A DIVERT -j ACCEPT
# now mark packets for the destination port 22 with 0x1 and
# set the tproxy port (our proxy) to 10022
iptables -t mangle -A PREROUTING -p tcp --dport 22 -j TPROXY --tproxy-mark 0x1/0x1 --on-port 10022

# this rule will do policy based routing: packets marked in the previously created
# rule will use routing table 100
ip rule add fwmark 1 lookup 100
# everything will be forwarded to localhost
ip route add local 0.0.0.0/0 dev lo table 100
```
